- client/src/components/Dashboard/views/marketer/Dashboard/ValueChart.jsx
- client/src/components/Main/index.jsx
- client/src/components/Main/views/CTA/ProductCTA.jsx
- client/src/components/Main/views/Login/BetaDialog.jsx
- service/app.js
- service/routes/creator.js
- service/routes/dashboard.js
- service/routes/login.js
- service/routes/mailer.js
- service/routes/marketer.js
- service/routes/regist.js
- docker logs 명령어를 이용하여 console을 확인하니 res가 출력되는 것을 수정하였습니다.
- 클로즈 베타종료 알림을 위한 Dialog 구현을 하였습니다.
> [UPDATE]  chan => dev  클로즈 베타 종료 관련

- README.md
- client/src/components/Common/ShutDownCloseBeta.jsx
- client/src/components/Dashboard/components/Navbars/AdminNavbarLinks.jsx
- client/src/components/Dashboard/components/Navbars/Notification.jsx
- client/src/index.jsx
1. Notifications for Closebeta shutdown
2. Page for closebeta shutdown
> [UPDATE] Hwasurr -> dev

- client/src/components/Common/NotFound.jsx
- client/src/components/Common/ShutDownCloseBeta.jsx
- client/src/components/Dashboard/components/Navbars/AdminNavbarLinks.jsx
- client/src/components/Dashboard/components/Navbars/Notification.jsx
- client/src/components/Dashboard/components/Table/Table.jsx
- client/src/components/Dashboard/views/creator/Dashboard/Dashboard.jsx
- client/src/components/Main/views/Login/BetaDialog.jsx
- client/src/index.jsx
- service/passportStrategy.js
1. 클로즈베타 종료 공지 페이지 글귀 / 레이아웃 수정
2. notfound 페이지 레이아웃 수정
3. dev 환경과 production 환경의 component routing 분기처리.
> [Update] Hwasurr 1 -> dev

- client/src/organisms/creator/Dashboard/BannerCard.jsx
- client/src/organisms/creator/Dashboard/Contraction/Contraction.jsx
- client/src/organisms/creator/Dashboard/ContractionCard.jsx
- client/src/organisms/creator/Dashboard/IncomeCard.jsx
- client/src/organisms/marketer/BannerManage/DeleteDialog.jsx
- client/src/organisms/marketer/CampaignCreate/OptionPaper.jsx
- client/src/organisms/marketer/Dashboard/CampaignCreate.jsx
- client/src/organisms/marketer/Dashboard/CampaignOnOffSwitch.jsx
- client/src/organisms/marketer/Dashboard/sub/CampaignTable.jsx
- service/routes/dashboard/creator/creator.js
- service/routes/dashboard/marketer/marketer.js
- service/routes/dashboard/marketer/sub/banner.js
- service/routes/dashboard/marketer/sub/campaign.js
- service/routes/dashboard/marketer/sub/category.js
> [SPRINT #4] 캠페인 생성 부분 수정

- client/src/organisms/main/Main/source/sources.jsx
- client/src/organisms/main/Main/views/Categories/ProductCategoriesImageButton.jsx
- client/src/organisms/main/Main/views/HowItWorks/ProductHowItWorks.jsx
> update phone number

- chat/index.js
- client/src/atoms/Navbars/AdminNavbarLinks.jsx
- service/app.js
- service/middlewares/slack/message.js
- service/passportStrategy.js
- service/routes/dashboard/marketer/sub/notification.js
- marketer notification 쿼리 오타 수정
- api 서버 오류시 슬랙알림 추가
- api 서버 오류시 로그남기는 형태 변경
> [update 2.1] Hwasurr -> dev

- client/.gitignore
- client/package.json
- client/src/index.jsx
- client/src/organisms/creator/Dashboard/WithdrawDialog.jsx
- client/src/organisms/creator/Manual/sources.jsx
- client/src/organisms/marketer/Dashboard/CampaignList.jsx
- client/src/organisms/marketer/Dashboard/MarketerReportLayout.jsx
- client/src/organisms/marketer/Dashboard/sub/CampaignTable.jsx
- client/src/organisms/marketer/Dashboard/sub/IpToGeo.jsx
- client/src/organisms/marketer/Dashboard/sub/MarketerReport.jsx
- client/src/organisms/marketer/Dashboard/sub/TabsReport.jsx
- client/src/pages/layouts/MarketerDashboardLayout.jsx
- client/src/pages/marketer/Dashboard.jsx
- service/routes/dashboard/marketer/sub/campaign.js
- service/routes/dashboard/marketer/sub/geo.js
크리에이터 - 출금신청 관련 고지 / 이용안내 obs 배너 삭제 내용 추가
마케터 - 보고서 작업중
> hwasurr => dev

- client/src/atoms/Chart/ReportStackedBar.jsx
- client/src/organisms/marketer/Dashboard/sub/IpToGeo.jsx
- client/src/organisms/marketer/Dashboard/sub/IpToGeoTable.jsx
- client/src/organisms/marketer/Dashboard/sub/MarketerReport.jsx
- client/src/organisms/marketer/Dashboard/sub/ReportTabsCard.jsx
- client/src/organisms/marketer/Dashboard/sub/TabsReport.jsx
- service/routes/dashboard/marketer/sub/report.js
- 보고서 그래프 수정
- ipToGeo 수정
- 보고서 style 수정
> [update 2.1] 보고서 그래프 수정/ipTOgeo 수정/보고서 style 수정

- chat/utils/now.js
> [twitch-chat] date month  수정

- client/src/organisms/main/Main/views/Carousel/MainCarousel.jsx
- client/src/organisms/main/Main/views/Carousel/MainCarousel.scss
- service/routes/api.js
1. 타이틀 생성 시점 조절 매끄럽게 하기
2. 무슨 이유인지는 모르겠지만 애니메이션과 데이터 불러오는 시점 차이가 생겼는데 해소시킴
> 캐러셀 크리에이터 데이터 10개 미만 시 예외처리 재작업

- node_websocket/public/requestImg.js
- service/socket_test.js
캠페인 onOff 가 1일 경우에도 marketer의 state에  따라 광고의 게시가 불가능하도록 변경
> [HOTFIX 3.1] 캠페인 onOff query 수정

- client/src/index.jsx
- production 에서, ThemeProvider 사용하여, custom theme 적용
> [update3.1 bugfix] production theme 적용

- calculator/javascripts/calculation_v.2.js
- client/src/organisms/marketer/CampaignCreate/CategorySelect.jsx
- service/getCreatorData.js
- service/routes/dashboard/creator/creator.js
- service/routes/regist/regist.js
> [HOTFIX 3.1] 계좌번호 암호화 정상화

- client/src/organisms/creator/BannerManage/sub/BannerTable.jsx
- client/src/organisms/creator/Dashboard/BannerDescPopover.jsx
- client/src/organisms/creator/Manual/sources.jsx
- client/src/organisms/marketer/BannerManage/BannerDescForm.jsx
- client/src/organisms/marketer/BannerManage/BannerTable.jsx
- client/src/organisms/marketer/BannerManage/UploadDialog.jsx
- client/src/organisms/marketer/CampaignCreate/CategorySelect.jsx
- client/src/organisms/marketer/CampaignCreate/OptionPaper.jsx
- client/src/organisms/marketer/Dashboard/banner/UploadDialog.jsx
- client/src/organisms/marketer/Dashboard/campaign/CampaignCreateDialog.jsx
- client/src/organisms/marketer/MyOffice/UserManage/SignOut.jsx
- client/src/organisms/marketer/MyOffice/UserManage/SignOutDialog.jsx
- client/src/pages/marketer/MyOffice.jsx
- email/app.js
- email/bin/log/.095c09e3523e69374ed428d1a39c4cde0127627b-audit.json
- email/bin/log/.4656d4b69a1bdd3f78a7960fb7be9313031a78bb-audit.json
- email/model/doDelete.js
- email/model/select.js
- email/model/separator.js
- service/routes/dashboard/creator/sub/banner.js
- service/routes/dashboard/marketer/sub/banner.js
- service/routes/dashboard/marketer/sub/campaign.js
- service/routes/dashboard/marketer/sub/profile.js
> [#Sprint 3.2]Leejineun -> dev

- client/src/organisms/marketer/CampaignCreate/CampaignCreateTable.jsx
- client/src/organisms/marketer/CampaignCreate/LandingUrlInput.jsx
- client/src/organisms/marketer/CampaignCreate/PriorityPaper.jsx
- client/src/pages/marketer/CampaignCreation.jsx
- service/routes/dashboard/marketer/sub/campaign.js
> [Sprint 4.2] Leejineun -> dev

- calculator/javascripts/calculation_v.3.js
> [UPDATE #4.2] 올바른 송출이 아닌 크리에이터의 경우 검거하기 기능 추가

- client/src/organisms/main/Main/views/Advantage/Advantage.jsx
- client/src/organisms/main/Main/views/HowToUse/HowToUse.jsx
- client/src/organisms/main/Main/views/IntroService/IntroService.jsx
- client/src/organisms/main/Main/views/Login/LoginForm.jsx
- client/src/organisms/main/Regist/RegistDialog.jsx
마케터 서비스 소개탭에서 회원가입 누를시에 소셜미디어 이미지 로드 되지 않는 현상 수정
> Hotfix motiv

- client/src/atoms/Chart/ReChartPie.jsx
- client/src/organisms/marketer/CampaignCreate/sub/ContentsPie.jsx
> [BUG fIX] legend 조건걸기

- server/@types/session.ts
- server/app.ts
- server/middlewares/responseHelper/helper.ts
- server/routes/test.ts
- send함수
`res.sendStatus().json() => res.status().json()`
- api라우터 => tsst 라우터
- getSessionData type오류 제거
> api server responseHelper 버그수정

- calculator/javascripts/getCreatorDetailData.js
- query 문 수정 오류
> 날짜 string 추가시 '' 필요
- data update시, follower수는 갱신하지 않도록 수정.
- follower 수가 0인 creator에 대해서는 다시 한번 더 확인 코드 추가
> [UPDATE #6.1] dev <= Chan

- calculator/javascripts/calculation_v.3.js
- client-ts/src/organisms/mypage/marketer/campaign-create/sub/CreatorSelect.tsx
- client-ts/src/organisms/mypage/marketer/dashboard/CashPopper.tsx
- client-ts/src/organisms/mypage/marketer/dashboard/DescCard.tsx
- client-ts/src/pages/mypage/marketer/Dashboard.tsx
1. 마케터 대시보드 충전 버튼 구현
> Popper  + MenuList 사용.
2. 캠페인 Log 관련 업데이트
> 크리에이터 선택형 선택 제한 ~~3명~~ => 1명
> campaignLog에 viewer col 생성 및 값 추가.
> [UPDATE #6.2] Chan => dev

- calculator/app.js
- calculator/javascripts/landingCalculator_v.1.js
- calculator/javascripts/trackingCalculator.js
광고페이지를 통한 광고클릭 및 챗봇을 통한 광고클릭 비율 변경
> [UPDATE #6.2] 클릭에 대한 크리에이터 수익 비율 변경

- server/app.ts
- tracker/app.ts
cors multiple origin 설정 - 테스트서버를 위해
tracker 버그 수정 - 애드픽 에서 302 redirect로 바꿔달라고 요청
> cors multiple origin 설정, tracker 버그 수정

- client-ts/test-task-definition.json
client-ts test task definition
> fix memoryReservation

- adpage-ts/src/organisms/Campaigns/CPACampaignList.jsx
- adpage-ts/src/organisms/Landing/LandingImages.jsx
- adpage-ts/src/organisms/LandingMain.jsx
- calculator/javascripts/trackingCalculator_v.3.js
- creatorId 부재시 계산 방지
- OS호환이 불가능한 앱의 경우 접속 방지
> [UPDATE #7.3] creatorId 부재시 tracking calculator 계산 방지

- client-ts/src/organisms/mypage/creator/CPAManage/CPAAgreement.style.ts
- client-ts/src/organisms/mypage/creator/CPAManage/CPAAgreement.tsx
> [Hotfix 7.3.3] Luke => Dev

- server/routes/cpapage/index.ts
- server/routes/creator/cpa/index.ts
> fix cpa income rate

- client-ts/src/organisms/main/regist/PlatformRegistForm.tsx
- client-ts/src/organisms/main/regist/RegistForm.tsx
- client-ts/src/organisms/main/regist/Stepper.reducer.ts
- server/routes/marketer/profile/index.ts
"사업자 등록번호" 데이터는 사용하지 않음 + 아무도 입력하려하지 않음
원래 사업자 등록번호는 세금계산서 발행을 위한 것. 하지만 현재 세금계산서 발행에 사용 되는 것은 사업자등록번호스캔본 사진.
사업자 등록번호도 해당 스캔본에 명시되어 있음
> 회원가입에서 사업자 등록번호 입력 삭제

- client-ts/src/organisms/main/notice/NoticeTable.tsx
- client-ts/src/organisms/mypage/marketer/office/business/BusinessUploadForm.tsx
- client-ts/src/organisms/mypage/marketer/office/business/businessuploadstep/BusinessUploadStep.tsx
- client-ts/yarn.lock
1) 변경하기클릭시 세금계산서 / 현금 영수증 모두 스탭 1에서 시작하도록 변경
2) pdfRex 정규 표현식을 추가하여 pdf파일 처리 구문 추가
> 변경하기 클릭시 step1 에서 시작 , pdf 파일 정규표현식 분기처리

- client-ts/src/organisms/mypage/creator/CampaignManage/NowBroadCard.tsx
- client-ts/src/organisms/mypage/creator/Dashboard/BannerCard.tsx
- client-ts/src/organisms/mypage/creator/RemotePage/sub/RemotePageOpenButton.tsx
- client-ts/src/organisms/mypage/creator/shared/StartGuideCard.tsx
- client-ts/src/pages/mypage/creator/Dashboard.tsx
- client-ts/src/pages/mypage/creator/MyAds.tsx
- 시작가이드에서 이용 동의시 데이터 새로 요청 - remoteUrl 데이터도 새로 요청 추가
- remoteUrl 버튼 데이터 없는경우 disabled 기능 추가
> [테스트 서버 배포 3]

- client-ts/src/organisms/mypage/layouts/Navbars/AdminNavbarLinks.tsx
- client-ts/src/organisms/mypage/marketer/office/cash/MyCash.tsx
- client-ts/src/pages/main/Main.tsx
- client-ts/src/pages/mypage/creator/Dashboard.tsx
- client-ts/src/pages/mypage/creator/IncomeManage.tsx
- client-ts/src/pages/mypage/creator/Manual.tsx
- client-ts/src/pages/mypage/creator/MyAds.tsx
- client-ts/src/pages/mypage/creator/Mypage.tsx
- client-ts/src/pages/mypage/layouts/CreatorLayout.tsx
- client-ts/src/pages/mypage/layouts/MarketerLayout.tsx
- client-ts/src/pages/mypage/marketer/CampaignCreate.tsx
- client-ts/src/pages/mypage/marketer/Dashboard.tsx
- client-ts/src/pages/mypage/marketer/Inventory.tsx
- client-ts/src/pages/mypage/marketer/Manual.tsx
- client-ts/src/pages/mypage/marketer/MyInfo.tsx
- client-ts/src/pages/mypage/marketer/MyOffice.tsx
- client-ts/src/pages/mypage/shared/Notice.tsx
- client-ts/src/utils/hooks/useMypageScrollToTop.tsx
- 광고주 상단 네비바 유저로고 기본이미지로 보이도록 수정
- 마케터 캐시 관리 - 버튼 variant 통일화
- 공지사항 개별 공지글 선택시 위로 스크롤링 추가
- 망이페이지 탭 변경시 top으로 스크롤링 기능 추가
>  [온애드 리뉴얼 3차 배포] Dev -> master 자잘한 버그 수정

- client-ts/src/organisms/mypage/shared/notice/NoticeTable.tsx
- 번호컬럼 너비 수정 + 메뉴버튼제거 추가
- 구분컬럼 너비 수정
해당 부분 dev에 반영 안되어있어 다시 올립니다
> 공지사항 방송인/광고주 구분 추가

- chatbot-twitch/task-definition.json
modify chatbot twitch taskdefinition.json
> [hotfix] 챗봇 배포 환경변수 설정 오류 수정

- afreeca-link-note-crawl/lib/afreeca/afreeca_crawler.py
- client-ts/src/organisms/main/popup/EventDialog.tsx
- client-ts/src/organisms/mypage/layouts/Navbars/AdminNavbarLinks.tsx
- client-ts/src/pages/mypage/creator/ReferralCodeManage.tsx
- server/routes/creator/referral-code/index.ts
Add: 아프리카 쪽지 인증 크롤러 추천인 코드 상태 변경 작업 로깅 추가
Fix: 추천인코드 메인팝업 글자 색상 theme에 상관없이 고정
Fix: 네비바 데이터 로딩 중 아바타 2개뜨는 현상 수정
Fix and Update: 이용 미동의시 분기처리 추가 및 추천인 코드 조회 쿼리 수정
> 추천인코드 hotfix 

- client-ts/src/atoms/Chart/ReChartBar.tsx
- client-ts/src/organisms/mypage/marketer/adManage/campaign/sub/CampaignDetail.tsx
- client-ts/src/organisms/mypage/marketer/adManage/merchandise/MerchandiseDeleteDialog.tsx
- client-ts/src/organisms/mypage/marketer/shared/MerchandiseUploadDialog.tsx
- client-ts/src/organisms/mypage/marketer/shared/settlement/SettlementRegDialog.tsx
- client-ts/src/organisms/mypage/marketer/shared/settlement/SettlementRegForm.tsx
- client-ts/src/organisms/mypage/marketer/shared/sub/MerchandiseAddressInput.tsx
- client-ts/src/utils/hooks/useImageListUpload.tsx
- server/routes/marketer/ad/analysis.ts
- server/routes/marketer/campaign/cpsAnalysis.ts
- server/routes/marketer/campaign/index.ts
- server/routes/marketer/inventory/merchandisePickupAddress.ts
- server/routes/marketer/inventory/merchandises.ts
- server/routes/marketer/profile/settlement.ts
- server/routes/marketer/profile/settlementLogs/settlementLogs.ts
Add: 상품등록 - 상품 히스토리 기능 추가
Fix: 캠페인에 할당되지 않은 상품도 할당되어 있다고 표시되는 버그 수정
Fix: 주소 내역 Chip 간 간격 추가
Fix: 주소 내역 동일한 내역은 불러오지 않도록 변경
Fix: 상품등록 - 재고, 상품금액 음수 입력 불가 처리 추가
Fix: 상품 등록 - 옵션 가격 음수 입력 불가 처리 추가
Add: 상품 등록 완료시 모든 입력값 리셋 기능 추가
Fix: 캠페인 정보 다이얼로그 - 상품재고 상태 표현 변경
Fix: 판매대금정산처리목록조회 일별로변경, 정산등록form 오류수정
Fix: 하드코딩 제거 및 campaignLog 테이블 레퍼런스 변경
Fix: 정산 처리 목록 날짜기준 내림차순 정렬 추가
Fix: 수익금 차트 숫자 "," 추가
> Hwasurr cps address history

- server/routes/marketer/inventory/merchandises.ts
> [CPS Beta] 슬랙 알림 기능 추가

- calculator/javascripts/calculation_v.4.js
- calculator/javascripts/trackingCalculator_v.3.js
- client-ts/src/organisms/main/main/login/CreatorLoginForm.tsx
- client-ts/src/organisms/mypage/creator/CampaignManage/BannerList.tsx
- client-ts/src/organisms/mypage/marketer/adManage/banner/BannerInventory.tsx
- client-ts/src/organisms/mypage/marketer/dashboard/CampaignList.tsx
- client-ts/src/organisms/mypage/marketer/shared/BannerUploadDialog.tsx
- client-ts/src/organisms/mypage/marketer/shared/sub/BannerUpload.tsx
- client-ts/src/utils/isVideo.ts
- server/lib/AWS/S3.ts
- server/lib/AWS/banner-migration-by-hwasurr-210412/migrate.ts
- server/lib/decodeBase64Banner.ts
- server/package.json
- server/routes/creator/banner/index.ts
- server/routes/creator/remote/remote.ts
- server/routes/marketer/ad/analysis.ts
- server/routes/marketer/ad/index.ts
- server/routes/marketer/campaign/campaignFuncs.ts
- server/routes/marketer/inventory/banner.ts
- server/yarn.lock
- socket/public/callImg.ts
- socket/public/client.ts
49baff2 커밋의 내용만 확인하시면 됩니다. @chanuuuuu @leejineun
> Hwasurr cps onoff

- client-ts/src/atoms/StaticInput.tsx
- client-ts/src/organisms/main/regist/PlatformRegistForm.tsx
- client-ts/src/organisms/main/regist/RegistForm.tsx
- client-ts/src/organisms/main/regist/Stepper.reducer.ts
- client-ts/src/organisms/main/regist/style/PlatformRegistForm.style.ts
- client-ts/src/organisms/main/regist/style/RegistForm.style.ts
- client-ts/src/utils/inputs/area-codes.ts
- client-ts/src/utils/inputs/regex/companyNum.regex.ts
- 기존의 StyledInput을 사용하려 하였으나 Select 컴포넌트와의 호환으로 인해 새 Input 구현. 
> 실제 StyledInput에 대한 스타일 적용불가로 인해 
- 마케터 회원가입 및 플랫폼 회원가입 각 구현완료
- 마케터 회원가입 테스트 완료
> markter 회원가입시 지역번호 선택형 구현

- client-ts/package.json
- client-ts/src/constants/banks.ts
- client-ts/src/organisms/mypage/creator/IncomeManage/Settlement/Settlement.reducer.ts
- client-ts/src/organisms/mypage/creator/IncomeManage/Settlement/SettlementForm.tsx
- client-ts/src/organisms/mypage/marketer/office/AccountRegistDialog.tsx
- client-ts/src/organisms/mypage/marketer/office/refund/RefundAccountManage.tsx
- client-ts/src/organisms/mypage/marketer/shared/settlement/SettlementRegDialog.tsx
- client-ts/src/organisms/mypage/marketer/shared/settlement/SettlementRegForm.tsx
- client-ts/yarn.lock
1. 은행 목록 추가 및 정리
2. 은행 선택 필드를 자동완성 필드로 변경
> [proj.2] Hwasurr fix banks

- client-ts/src/pages/main/Main.tsx
- server/routes/marketer/orders/index.ts
- 기존 팝업 제거, 추천인코드 팝업으로 변경
- 쿼리 오타 수정
> Hot update popup

- live-commerce/.gitignore
- live-commerce/app.ts
- live-commerce/lib/client.ts
- 여러 아이디가 접속하면 특정 아이디의 소켓 아이디 받아오지 못하는 현상 수정
- 구매알람 단계설정 하지 않으면 1단계 알람음이 기본
> [BUGFIX] 라이브 커머스 서버 버그 픽스

- .prettierrc
- api/src/setting/appSetting.ts
s3 aws access key, secret 인터넷 노출 -> 변경 트리거
> Add: next 배포 준비를 위한 화이트리스트 추가 + s3key배포 트리거

- api/src/resources/creator/clicks/clicks.controller.ts
- api/src/resources/creator/clicks/clicks.service.ts
- client-ts/src/organisms/mypage/creator/CampaignManage/AdClickCard.tsx
- client-ts/src/organisms/mypage/creator/CampaignManage/ClickAdInfo.tsx
- client-ts/src/organisms/mypage/creator/Dashboard/ClickAdCard.tsx
- client-ts/src/organisms/mypage/creator/shared/AdIncomeCard.tsx
- client-ts/src/pages/mypage/creator/Dashboard.tsx
- client-ts/src/pages/mypage/creator/campaign/CampaignManage.tsx
- client-ts/src/utils/hooks/query/useCreatorClicks.ts
> HotFix: 채팅광고 제어 제거

- client-ts/package.json
- client-ts/src/organisms/main/layouts/NavTop.tsx
- client-ts/src/organisms/main/main/login/CreatorLoginForm.tsx
- client-ts/src/organisms/main/main/login/MarketerLoginForm.tsx
- client-ts/src/pages/main/Main.tsx
- client-ts/src/pages/main/Regist.tsx
- client-ts/src/pages/main/RegistCreator.tsx
- client-ts/yarn.lock
- 신규 가입 방지
- 방송인 아프리카TV 플랫폼 추가 팝업 제거
- 모든 광고 송출 중지
> 서비스 종료 1차 변경사항
